import { InjectorToken } from '@fm/di';
export const UI_ELEMENT = InjectorToken.get('UI_ELEMENT');
export const ACTIONS_CONFIG = InjectorToken.get('ACTION_CONFIG');
export const ACTION_INTERCEPT = InjectorToken.get('ACTION_INTERCEPT');
export const BUILDER_EXTENSION = InjectorToken.get('BUILDER_EXTENSION');
export const LOAD_BUILDER_CONFIG = InjectorToken.get('LOAD_BUILDER_CONFIG');
export const FACTORY_BUILDER = InjectorToken.get('FACTORY_BUILDER');
export const BIND_FORM_CONTROL = InjectorToken.get('BIND_FORM_CONTROL');
export const BIND_BUILDER_ELEMENT = InjectorToken.get('BIND_BUILDER_ELEMENT');
export const VALIDATOR_SERVICE = InjectorToken.get('VALIDATOR_SERVICE');
export const GET_JSON_CONFIG = InjectorToken.get('GET_JSON_CONFIG');
