import { InjectorToken } from '@fm/di';
export const UI_ELEMENT = InjectorToken.get('UI_ELEMENT');
export const GET_TYPE = InjectorToken.get('GET_TYPE');
export const ACTIONS_CONFIG = InjectorToken.get('ACTION_CONFIG');
export const CONVERT_CONFIG = InjectorToken.get('CONVERT_CONFIG');
export const ACTION_INTERCEPT = InjectorToken.get('ACTION_INTERCEPT');
export const CONVERT_INTERCEPT = InjectorToken.get('CONVERT_INTERCEPT');
export const BUILDER_EXTENSION = InjectorToken.get('BUILDER_EXTENSION');
export const LOAD_BUILDER_CONFIG = InjectorToken.get('LOAD_BUILDER_CONFIG');
export const FACTORY_BUILDER = InjectorToken.get('FACTORY_BUILDER');
export const FORM_CONTROL = InjectorToken.get('FORM_CONTROL');
export const LAYOUT_ELEMENT = InjectorToken.get('LAYOUT_ELEMENT');
export const GET_JSON_CONFIG = InjectorToken.get('GET_JSON_CONFIG');
