"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.serializeAction = exports.BuilderModel = exports.Grid = exports.useBuilderContext = exports.InjectableValidator = void 0;
const tslib_1 = require("tslib");
const di_1 = require("@fm/di");
const token_1 = require("../token");
const basic_extension_1 = require("./basic/basic.extension");
Object.defineProperty(exports, "serializeAction", { enumerable: true, get: function () { return basic_extension_1.serializeAction; } });
const builder_context_1 = require("./context/builder-context");
const InjectableValidator = () => (0, di_1.Injectable)(token_1.VALIDATOR_SERVICE);
exports.InjectableValidator = InjectableValidator;
const useBuilderContext = () => new builder_context_1.BuilderContext();
exports.useBuilderContext = useBuilderContext;
tslib_1.__exportStar(require("./action"), exports);
tslib_1.__exportStar(require("./action/create-actions"), exports);
tslib_1.__exportStar(require("./basic/basic.extension"), exports);
tslib_1.__exportStar(require("./constant/calculator.constant"), exports);
tslib_1.__exportStar(require("./form/type-api"), exports);
var grid_1 = require("./grid/grid");
Object.defineProperty(exports, "Grid", { enumerable: true, get: function () { return grid_1.Grid; } });
var builder_extension_model_1 = require("./model/builder-extension-model");
Object.defineProperty(exports, "BuilderModel", { enumerable: true, get: function () { return builder_extension_model_1.BuilderModelExtensions; } });
tslib_1.__exportStar(require("./type-api"), exports);
tslib_1.__exportStar(require("./view-model/base.view"), exports);
