import { InjectorToken } from '@fm/di';
export declare const UI_ELEMENT: InjectorToken;
export declare const GET_TYPE: InjectorToken;
export declare const ACTIONS_CONFIG: InjectorToken;
export declare const CONVERT_CONFIG: InjectorToken;
export declare const ACTION_INTERCEPT: InjectorToken;
export declare const CONVERT_INTERCEPT: InjectorToken;
export declare const BUILDER_EXTENSION: InjectorToken;
export declare const LOAD_BUILDER_CONFIG: InjectorToken;
export declare const META_TYPE: InjectorToken;
export declare const META_PROPS: InjectorToken;
export declare const SCOPE_PROPS: InjectorToken;
export declare const SCOPE_MODEL: InjectorToken;
export declare const GRID_PARSE: InjectorToken;
export declare const FACTORY_BUILDER: InjectorToken;
export declare const FORM_CONTROL: InjectorToken;
export declare const LAYOUT_ELEMENT: InjectorToken;
export declare const GET_JSON_CONFIG: InjectorToken;
