import { InjectorToken } from '@fm/di';
export declare const UI_ELEMENT: InjectorToken;
export declare const ACTIONS_CONFIG: InjectorToken;
export declare const ACTION_INTERCEPT: InjectorToken;
export declare const BUILDER_EXTENSION: InjectorToken;
export declare const LOAD_BUILDER_CONFIG: InjectorToken;
export declare const FACTORY_BUILDER: InjectorToken;
export declare const BIND_FORM_CONTROL: InjectorToken;
export declare const BIND_BUILDER_ELEMENT: InjectorToken;
export declare const VALIDATOR_SERVICE: InjectorToken;
export declare const GET_JSON_CONFIG: InjectorToken;
