import { serializeAction } from './basic/basic.extension';
import { BuilderContext } from './context/builder-context';
export declare const InjectableValidator: () => <T>(target: import("@fm/di").Type<T>) => import("@fm/di").Type<T>;
export declare const useBuilderContext: () => BuilderContext;
export * from './action';
export * from './action/create-actions';
export * from './basic/basic.extension';
export * from './constant/calculator.constant';
export * from './form/type-api';
export { Grid } from './grid/grid';
export { BuilderModelExtensions as BuilderModel } from './model/builder-extension-model';
export * from './type-api';
export * from './view-model/base.view';
export { serializeAction };
